Input Notebook:  18_LAMLP_Massive_test_all_taxonomy_15_Oct_2023.ipynb
Output Notebook: metrics_global_loss_composed/no_clean/ipynbs/res_18_noclean_allmeltome_global.ipynb
Traceback (most recent call last):
  File "/z/home/sgal/miniconda3/envs/thermoPML/lib/python3.9/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/z/home/sgal/miniconda3/envs/thermoPML/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/z/home/sgal/miniconda3/envs/thermoPML/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/spool/slurmd/job173154/slurm_script", line 8, in <module>
    sys.exit(papermill())
  File "/z/home/sgal/miniconda3/envs/thermoPML/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/z/home/sgal/miniconda3/envs/thermoPML/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/z/home/sgal/miniconda3/envs/thermoPML/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/z/home/sgal/miniconda3/envs/thermoPML/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/z/home/sgal/miniconda3/envs/thermoPML/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/z/home/sgal/miniconda3/envs/thermoPML/lib/python3.9/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/z/home/sgal/miniconda3/envs/thermoPML/lib/python3.9/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/z/home/sgal/miniconda3/envs/thermoPML/lib/python3.9/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/z/home/sgal/miniconda3/envs/thermoPML/lib/python3.9/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/z/home/sgal/miniconda3/envs/thermoPML/lib/python3.9/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/z/home/sgal/miniconda3/envs/thermoPML/lib/python3.9/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '18_LAMLP_Massive_test_all_taxonomy_15_Oct_2023.ipynb'
